### ISSUE TITLE
Does nnscaler support fp16/bf16?

### ISSUE THREAD

**Issue by MachineGunLin** [microsoft/nnscaler#11]
According to [mapping.py](https://github.com/microsoft/nnscaler/blob/main/nnscaler/graph/parser/fx/mapping.py#L100), seems like nnscaler doesn't support fp16 and bf16.

I am wondering do you have any plans to support those dtype?

**Comment by zyeric** [comment]
bf16/fp16 is supported. please check the examples below:

- https://github.com/microsoft/nnscaler/blob/main/examples/llama3_demo/train.py#L263
- https://github.com/microsoft/nnscaler/blob/main/examples/llama3_8B_128K/train.py#L227
